name: flutter_data_demo
description: "A comprehensive Flutter app demonstrating local and server data management with SQLite, JSON, Excel, and Supabase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # SQLite database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # File handling
  file_picker: ^6.1.1
  
  # JSON handling
  http: ^1.2.0
  
  # Excel handling
  excel: ^2.1.0
  
  # Supabase integration
  supabase_flutter: ^2.3.4
  
  # UI enhancements
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/json/
    - assets/excel/ 