name: flutter_sqlite_crud
description: "A Flutter app with SQLite database and JSON file handling."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # SQLite database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # File handling
  file_picker: ^6.1.1
  
  # JSON handling
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/json/
